services:
  postgres:
    image: postgres:16
    container_name: finance_postgres
    restart: always
    ports:
      - "5444:5432"              
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: finance
    volumes:
      - ../db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: